[project]
name = "dating-quiz-bot"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "aiogram==3.22.0",
    "aiohttp==3.12.15",
    "httpx==0.28.1",
    "pydantic-settings==2.10.1",
]

[dependency-groups]
dev = [
    "ruff>=0.13.2",
    "mypy>=1.18.1",
]
